<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Assignment">
    <meta name="keywords" content="HTML, CSS, JavaScript">
    <meta name="author" content="Le Minh">
    <title>Enhancement #1</title>
    <link rel="stylesheet" type="text/css" href="styles/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<header class="header">
    <a href="index.php" class="logo">InnoTech</a>
    <nav class="nav-items">
        <a href="index.php">Home</a>
        <a href="jobs.php">Jobs</a>
        <a href="apply.php">Apply</a>
        <a href="about.php">About</a>
        <a href="enhancements.php">Enhancement #1</a>
        <a href="enhancements2.php">Enhancement #2</a>
        <a href="phpenhancements.php">PHP Enhancements</a>
        <a href="manage.php">Manage</a>
    </nav>
</header>
<h2>Enhancement #1</h2>
<p>All the content inside is generated by ChatGPT:<a href=" https://openai.com/blog/chatgpt"> https://openai.com/blog/chatgpt</a></p>
<h2>Enhancement</h2>
<p>Footer Icon learned from W3School: <a href="https://www.w3schools.com/howto/howto_css_social_media_buttons.asp">https://www.w3schools.com/howto/howto_css_social_media_buttons.asp</a></p>
<p>Text over background picture: <a href="https://www.w3schools.com/howto/howto_css_image_text.asp">https://www.w3schools.com/howto/howto_css_image_text.asp</a></p>
<footer>
  <div class="footer-content">
      <div class="footer-section">
          <h4>Follow me</h4>
          <a href="https://www.facebook.com/" class="fa fa-facebook"></a>
          <a href="https://au.linkedin.com/" class="fa fa-linkedin"></a>
          <a href="https://twitter.com/?lang=en" class="fa fa-twitter"></a>
          <a href="https://www.youtube.com/" class="fa fa-youtube"></a>
          <a href="https://www.snapchat.com/" class="fa fa-snapchat-ghost"></a>
      </div>
  </div>
  <div class="footer-bottom">
    <p>Email: <a href="mailto:104103262@student.swin.edu.au">104103262@student.swin.edu.au</a></p>
    <p>© Le Minh - 104103262</p>
  </div>
</footer>
<script src="scripts/enhancements.js"></script>
<script src="scripts/apply.js"></script>
</body>
</html>