<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Assignment">
    <meta name="keywords" content="HTML, CSS, JavaScript">
    <meta name="author" content="Le Minh">
    <title>Jobs</title>
    <link rel="stylesheet" type="text/css" href="styles/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<header class="header">
    <a href="index.php" class="logo">InnoTech</a>
    <nav class="nav-items">
        <a href="index.php">Home</a>
        <a href="jobs.php">Jobs</a>
        <a href="apply.php">Apply</a>
        <a href="about.php">About</a>
        <a href="enhancements.php">Enhancement #1</a>
        <a href="enhancements2.php">Enhancement #2</a>
        <a href="phpenhancements.php">PHP Enhancements</a>
        <a href="manage.php">Manage</a>
    </nav>
</header>
      <div class="vision">
        <div class="vision-text">
            <h2>Internet of Things (IOT) developer - IOT01</h2>
            <p><b>Job Title:</b> IoT Developer</p>
            <p><b>Company:</b> InnoTech Solutions</p>
            <p><b>Location:</b> Silicon Valley, CA (Hybrid/Remote Options Available)</p>
            <p><b>Job Type:</b> Full-time</p>
            <b>About InnoTech Solutions:</b>
            <p>InnoTech Solutions is a globally recognized technology company specializing in cutting-edge IoT solutions. We are on a mission to empower businesses to harness the power of the Internet of Things to drive innovation, enhance operational efficiency, and create transformative experiences. Our team of passionate developers and engineers is at the forefront of IoT innovation, and we're looking for talented individuals to join us in shaping the future of connected technology.</p>
            <b>Job Overview:</b>
            <p>As an IoT Developer at InnoTech Solutions, you will play a pivotal role in designing, developing, and implementing IoT solutions that drive business growth and technological advancement. You will work in a dynamic and collaborative environment, utilizing your expertise in IoT technologies to create innovative solutions that address real-world challenges across various industries.</p>  
            <b>Key Responsibilities:</b>
            <ol>
                <li>IoT Solution Development: Design, develop, and deploy end-to-end IoT solutions, including hardware and software components, to meet client requirements.</li>
                <li>Sensor Integration: Integrate a wide range of sensors and devices into IoT ecosystems, ensuring seamless data collection and communication.</li>
                <li>Data Management: Develop robust data management and storage solutions to handle the vast amounts of data generated by IoT devices.</li>
                <li>Cloud Integration: Implement cloud-based IoT platforms for data storage, analysis, and visualization, leveraging services such as AWS IoT, Azure IoT, or Google Cloud IoT.</li>
                <li>Security: Implement robust security measures to protect IoT systems and data, including encryption, authentication, and access control.</li>
                <li>Data Analytics: Utilize data analytics and machine learning techniques to derive meaningful insights from IoT data streams.</li>
                <li>API Development: Create APIs for seamless integration of IoT solutions with client systems and third-party applications.</li>
                <li>Testing and Quality Assurance: Conduct thorough testing and debugging of IoT applications to ensure reliability and performance.</li>
                <li>Documentation: Maintain comprehensive documentation of IoT solution architecture, code, and configurations.</li>
                <li>Collaboration: Collaborate with cross-functional teams, including hardware engineers, data scientists, and project managers, to deliver successful IoT projects.</li>
            </ol>
            <b>Qualifications:</b>
            <ul>
                <li>Bachelor's degree in Computer Science, Electrical Engineering, or related field (Master's preferred).</li>
                <li>Proven experience in IoT development, including hands-on experience with IoT hardware and platforms.</li>
                <li>Proficiency in programming languages such as Python, C/C++, or Java.</li>
                <li>Strong understanding of IoT protocols (MQTT, CoAP, HTTP, etc.) and wireless communication technologies (e.g., Bluetooth, Wi-Fi, LoRa).</li>
                <li>Familiarity with cloud platforms (AWS, Azure, Google Cloud) and IoT services.</li>
                <li>Knowledge of data analytics and machine learning for IoT data.</li>
                <li>Excellent problem-solving skills and a passion for staying up-to-date with emerging IoT trends and technologies.</li>
            </ul>
            <b>Why Join InnoTech Solutions:</b>
            <ul>
            <li>Be at the forefront of IoT innovation.</li>
            <li>Work on exciting projects that impact various industries.</li>
            <li>Collaborative and inclusive work culture.</li>
            <li>Opportunity for professional growth and development.</li>
            <li>Competitive compensation and benefits package.</li>
            <li>Hybrid and remote work options for work-life balance.</li>
            </ul>
            <p>If you're a passionate IoT developer looking to make a meaningful impact in the world of connected technology, we invite you to join our team at InnoTech Solutions. Apply today to be a part of our journey in shaping the future of IoT.</p>
            <a href="apply.php" class="apply-btn" data-jobref="IOT01">Apply</a>
          </div>
      </div>
      <div class="vision">
        <div class="vision-text">
        <h2>Business Analyst - BA001</h2>
            <p><b>Job Title:</b> Business Analyst</p>
            <p><b>Company:</b> InnoTech Solutions</p>
            <p><b>Location:</b> Silicon Valley, CA (Hybrid/Remote Options Available)</p>
            <p><b>Job Type:</b> Full-time</p>
        <b>About InnoTech Solutions:</b>
        <p>InnoTech Solutions is a globally renowned technology company that specializes in cutting-edge IoT, AI, and digital transformation solutions. We are committed to driving innovation, empowering businesses, and shaping the future of technology. As a Business Analyst at InnoTech Solutions, you will have the opportunity to work on exciting and transformative projects that impact various industries.</p>
        <b>Job Overview:</b>
        <p>We are seeking a highly motivated and detail-oriented Business Analyst to join our dynamic team. As a Business Analyst, you will play a critical role in bridging the gap between business needs and technology solutions. You will collaborate with clients and internal teams to gather, analyze, and document requirements, ensuring successful project outcomes. Your insights and expertise will be instrumental in shaping IoT and technology solutions that drive our clients' success.</p>
        <b>Key Responsibilities:</b>
        <ol>
            <li>Requirement Elicitation: Collaborate with clients and stakeholders to gather, analyze, and document business requirements for IoT and technology projects.</li>
            <li>Business Process Analysis: Conduct thorough analysis of existing business processes and workflows to identify opportunities for improvement and optimization.</li>
            <li>Documentation: Create clear and comprehensive business requirement documents, use cases, user stories, and process flow diagrams.</li>
            <li>Data Analysis: Analyze data to identify trends, patterns, and insights that can inform decision-making and solution design.</li>
            <li>Solution Design Support: Work closely with the development and engineering teams to translate business requirements into technical specifications.</li>
            <li>Quality Assurance: Assist in defining test cases and acceptance criteria to ensure that delivered solutions meet business requirements.</li>
            <li>Stakeholder Communication: Act as a liaison between business stakeholders, project managers, and technical teams to facilitate effective communication and collaboration.</li>
            <li>Continuous Improvement: Identify opportunities for process improvement and provide recommendations to enhance project delivery and client satisfaction.</li>
        </ol>
        <b>Qualifications:</b>
        <ul>
        <li>Bachelor's degree in Business Administration, Computer Science, or a related field (Master's preferred).</li>
        <li>Proven experience as a Business Analyst in technology or IoT-related projects.</li>
        <li>Strong analytical and problem-solving skills.</li>
        <li>Proficiency in business analysis tools and methodologies.</li>
        <li>Excellent communication and interpersonal skills.</li>
        <li>Detail-oriented with a focus on delivering high-quality documentation.</li>
        <li>Familiarity with IoT, AI, and digital transformation concepts is a plus.</li>
        </ul>
        <b>Why Join InnoTech Solutions:</b>
        <ul>
        <li>Be part of a globally recognized technology company leading in innovation.</li>
        <li>Work on transformative projects that impact multiple industries.</li>
        <li>Collaborative and inclusive work environment.</li>
        <li>Opportunities for professional growth and development.</li>
        <li>Competitive compensation and benefits package.</li>
        <li>Hybrid and remote work options to support work-life balance.</li>
      </ul>
        <p>If you're a dedicated and detail-oriented Business Analyst with a passion for technology and innovation, we invite you to join our team at InnoTech Solutions. Apply today to contribute to the future of technology and make a significant impact on our clients' success.</p>
        <a href="apply.php" class="apply-btn" data-jobref="BA001">Apply</a>
      </div>
      </div>
      <footer>
        <div class="footer-content">
            <div class="footer-section">
                <h4>Follow me</h4>
                <a href="https://www.facebook.com/" class="fa fa-facebook"></a>
                <a href="https://au.linkedin.com/" class="fa fa-linkedin"></a>
                <a href="https://twitter.com/?lang=en" class="fa fa-twitter"></a>
                <a href="https://www.youtube.com/" class="fa fa-youtube"></a>
                <a href="https://www.snapchat.com/" class="fa fa-snapchat-ghost"></a>
            </div>
        </div>
        <div class="footer-bottom">
          <p>Email: <a href="mailto:104103262@student.swin.edu.au">104103262@student.swin.edu.au</a></p>
          <p>© Le Minh - 104103262</p>
        </div>
    </footer>
  <script src="scripts/enhancements.js"></script>
  <script src="scripts/apply.js"></script>
</body>
</html>
